version: '3'
services:
  app:
    build: .
    ports:
      - "4444:4444"
    depends_on:
      - db
  db:
    container_name: postgres_spendbase
    image: postgres:16.1-alpine
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"